name: recycling_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.3
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  skeletonizer: ^1.4.3
  location: ^5.0.3
  flutter_polyline_points: ^2.1.0
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
    - family: SeoulNamsan
      fonts:
        - asset: assets/fonts/seoul_namsan/SeoulNamsan-Regular.ttf